# Generated by Django 2.1.7 on 2021-01-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210124_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='userid',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='Password',
        ),
    ]
