# Generated by Django 2.1.7 on 2021-01-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210124_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='userid',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='Password',
        ),
    ]
